//-----------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//-----------------------------------------------------------------------
module internal rec Kedr.AST.Parser

type Terminal<'id, 'eq, 'asterisk> =
    | T_asterisk of 'asterisk
    | T_eq of 'eq
    | T_id of 'id

type Reducer<'id, 'eq, 'asterisk, 'S, 'R, 'L, 'E> = {
    E_L_eq_R : ('L * 'eq * 'R) -> 'E
    E_R : ('R) -> 'E
    L_asterisk_R : ('asterisk * 'R) -> 'L
    L_id : ('id) -> 'L
    R_L : ('L) -> 'R
    S_E : ('E) -> 'S
}

let parse<'token, 'id, 'eq, 'asterisk, 'S, 'R, 'L, 'E>
    (recognizeTerminal : 'token -> Terminal<'id, 'eq, 'asterisk>)
    (reducer : Reducer<'id, 'eq, 'asterisk, 'S, 'R, 'L, 'E>)
    (tokens : seq<'token>)
    : Result<'S, string> =
    failwith "TODO"
