namespace Kedr.AST

//-----------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//-----------------------------------------------------------------------

module Parser =
    type Symbol =
        | E
        | L
        | R
        | S
        | asterisk
        | eq
        | id
